### ISSUE TITLE
настройка микротика не срабатывает

### ISSUE THREAD

**Issue by DContr** [korsunav/mikrotik-wireguard-vless#1]
Привет! спасибо за мануал, V2rayA и WireGuard - настроил - всё работает, а вот настройка Микротика - нет, делаю все настройки, но результата нет, видно что трафик через wireguard Не идёт, подключения нет. Подскажи, куда копать 
![1](https://github.com/user-attachments/assets/934d9ea7-78bb-4b2e-b875-c68345fa0248)
![2](https://github.com/user-attachments/assets/1652d114-49a5-4564-9224-3b56ee483708)

**Comment by korsunav** [comment]
@DContr Hi!
Судя по скринам у тебя не работает туннель wireguard.
Покажи настройки IP - Addresses для интерфейса wg
Если все настройки по умолчанию, то должно выглятить так:
![изображение](https://github.com/user-attachments/assets/d4e7b963-022e-4c2e-a2a6-cb9fbc71bdfe)
кроме имени интерфейса. у тебя wg1

**Comment by DContr** [comment]
да, всё идентично. при этом сам wanguard если с телефона подключаюсь через QR отлично работает.

![3](https://github.com/user-attachments/assets/34fb9e7e-c5cf-4bd7-a139-e783300ef9ed)

Кстати, последняя команда, где добавляется сразу пачка сайтов у меня показывается с ошибкой, но я руками занёс нужные 


[admin@MikroTik] > wget -qO- https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst | sed "s
/.*/\/ip dns static add name=& type=FWD forward-to=8.8.8.8 address-list=vpn-domains match-subdomain=yes/"
syntax error (line 1 column 109)

**Comment by korsunav** [comment]
Последняя комманда выполняется не на Mikrotik. У Mikrotik нет wget. Выполни её в терминале Linux, а получившиеся комманды просто вставь пачкой в терминал Mikrotik

По поводу работы WG попробуй посмотреть tcpdump'ом прилетает ли вообще что-то на интерфейс ВМ. Если нет, то перепроверь настройки WG, NAT, отключи firewall.

Выкладывай настройки сюда, может увижу где ошибка

**Comment by DContr** [comment]
Перезалил конфиг вангуард и всё заработало.

Тормозила скорость соединения, помогло 

/ip firewall mangle 
add action=change-mss chain=forward new-mss=clamp-to-pmtu out-interface=wireguard protocol=tcp tcp-flags=syn

и отключение fasttrack

Ютуб всё равно не заводился, помогло добавление в фаервол адресов https://forummikrotik.ru/viewtopic.php?t=16909&start=90

**Comment by korsunav** [comment]
> Ютуб всё равно не заводился, помогло добавление в фаервол адресов https://forummikrotik.ru/viewtopic.php?t=16909&start=90

Есть важный момент.
Что бы работало авто заполнение address-list, нужно что бы DNS сервером для устройств в сети был сам Mikrotik.
Только в таком случае он будет смотреть на URL которые ему указали в DNS - Static и далее резолвить их и добавлять в address-list
